### PR TITLE
Update english word dictionary

### PR DESCRIPTION
**Pull request by cyb3rko**
#61

### CODE REVIEW

**Comment by Tostino** [comment]
So I haven't had time to pull this up and run tests, but I have a feeling that it'll change the results of some of the tests we have in there. If you get to it before me, that is probably going to require some tweaks to the tests before it can be merged.

**Comment by cyb3rko** [comment]
So what do you think should be changed?
Should I first of all test it out and see if they fail?

**Comment by Tostino** [comment]
Yeah just run the tests with maven and you'll see any that begin to fail. I'll get to it probably this weekend if you don't have time, but if you want to take a stab at it that would be appreciated.

**Comment by cyb3rko** [comment]
Ok, so two errors appeared.
I just changed the expected entropy for the values which failed.

Now the tests succeed again, is that what you expected me to do?
Because then I can add it to this pull request.

**Comment by Tostino** [comment]
Yeah that sounds right, add the changes and i'll review / merge. Thank you for identifying this, and taking the initiative to implement.

**Comment by cyb3rko** [comment]
Done

**Comment by Tostino** [comment]
Thanks! I do think I am going to look into why the password: ef00623ced862e84ea15a6f97cb3fbb9f177bd6f23e54459a96ca5926c28c653 jumped from ~247 bits of entropy all the way to ~337 bits though. I wouldn't have expected that password to have been affected by this change at all, as it should be identified as effectively "random".

**Comment by cyb3rko** [comment]
I'm currently developing an Android app for showing Nbvcxz analyze results in a handy way and it says that this password is considered random.

**Comment by Tostino** [comment]
So it looks like after we add all these extra words to the dictionary, we are getting that password marked as non-random. I actually think I remember why the list was different now, I believe it was because I culled all 2 letter words because they caused a bunch of false positives, especially with l33t substitution. 
I think this could be fixed by disabling that l33t substitution if the words are too short, or something of that nature.

**Comment by cyb3rko** [comment]
But even if you remove all words with only 2 letters, there should be many more words than there really are, right?
Mmh, maybe I can try to find how to supress l33t substition for short words, let's see.

**Comment by MrWook** [comment]
Just so you know `zxcvbn` doesn't use all those 100k lines of wikipedia entries. The file that you mentioned [english_wikipedia.txt](https://github.com/dropbox/zxcvbn/blob/master/data/english_wikipedia.txt) is the raw data file that will go through a parser in the build process. At the end there will be like 30k left.

[here](https://github.com/dropbox/zxcvbn/blob/master/data-scripts/count_wikipedia.py#L86) is the check which entries should be used and at the end everything less than 300 counts will be removed too.

**Pull request closed without merging**
